apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-app-project
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
    name: local-cluster
  sourceRepos:
  - '*'
