apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-app-set
  namespace: openshift-gitops
spec:
  generators:
  - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: demo-app-set-clusters
        requeueAfterSeconds: 180
  template:
    metadata:
      name: demo-app-set-{{name}}
    spec:
      project: apps-project
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/RedHat-EMEA-SSA-Team/ns-apps
        targetRevision: appsets
        path: apps/bgd
      destination:
        server: "{{server}}"
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: demo-app-set-clusters  
  namespace: openshift-gitops
spec:
  clusterSets:
    - all-clusters
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - dev