apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: with-label-placement
  namespace: openshift-gitops
spec:
  clusterSets:
  - all-clusters
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: environment
          operator: In
          values:
          - production