apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: webserver
  namespace: openshift-gitops
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"argoproj.io/v1alpha1","kind":"ApplicationSet","metadata":{"annotations":{},"name":"webserver","namespace":"openshift-gitops"},"spec":{"generators":[{"git":{"directories":[{"path":"04.Application-Lifecycle/exercise-argocd/application-resources/values/*"}],"repoURL":"https://github.com/michaelkotelnikov/rhacm-workshop.git","revision":"master"}}],"template":{"metadata":{"name":"{{path.basename}}"},"spec":{"destination":{"name":"local-cluster"},"project":"demo-project-argocd","source":{"helm":{"valueFiles":["values/{{path.basename}}/values.yaml"]},"path":"04.Application-Lifecycle/exercise-argocd/application-resources/","repoURL":"https://github.com/michaelkotelnikov/rhacm-workshop.git","targetRevision":"master"},"syncPolicy":{"automated":{"prune":false,"selfHeal":true}}}}}}
  creationTimestamp: 2022-12-07T10:17:50Z
  generation: 1
  resourceVersion: "1820010"
  uid: abc1c400-acde-4074-8635-1286e2df33d5
spec:
  generators:
    - git:
        directories:
          - path: 04.Application-Lifecycle/exercise-argocd/application-resources/values/*
        repoURL: https://github.com/michaelkotelnikov/rhacm-workshop.git
        revision: master
      clusterDecisionResource:
        requeueAfterSeconds: 180
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: all-clusters
  template:
    metadata:
      name: webserver-{{name}}
    spec:
      destination:
        name: local-cluster
        namespace: gitops-apps
      project: demo-project-argocd
      source:
        helm:
          valueFiles:
            - values/{{path.basename}}/values.yaml
        path: 04.Application-Lifecycle/exercise-argocd/application-resources/
        repoURL: https://github.com/michaelkotelnikov/rhacm-workshop.git
        targetRevision: master
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
status:
  conditions:
    - lastTransitionTime: 2022-12-07T10:17:51Z
      message: Successfully generated parameters for all Applications
      reason: ApplicationSetUpToDate
      status: "False"
      type: ErrorOccurred
    - lastTransitionTime: 2022-12-07T10:17:51Z
      message: Successfully generated parameters for all Applications
      reason: ParametersGenerated
      status: "True"
      type: ParametersGenerated
    - lastTransitionTime: 2022-12-07T10:17:51Z
      message: ApplicationSet up to date
      reason: ApplicationSetUpToDate
      status: "True"
      type: ResourcesUpToDate

